DELIMITER //
DROP FUNCTION IF EXISTS CALCULO_RECORRENCIA;
CREATE FUNCTION CALCULO_RECORRENCIA(DT_INICIO DATETIME, QTD_RECORRENCIAS INT, 
	TIPO_RECORRENCIA INT) RETURNS DATETIME DETERMINISTIC
BEGIN
	DECLARE DATA_RETORNO DATETIME;

	IF TIPO_RECORRENCIA = 0 OR TIPO_RECORRENCIA IS NULL THEN
		SET DATA_RETORNO = DT_INICIO; 
    END IF;
    
    IF TIPO_RECORRENCIA = 1 THEN
		SET DATA_RETORNO = DATE_ADD(DT_INICIO, INTERVAL QTD_RECORRENCIAS DAY);
    END IF;
    
    IF TIPO_RECORRENCIA = 2 THEN
		SET DATA_RETORNO = DATE_ADD(DT_INICIO, INTERVAL QTD_RECORRENCIAS WEEK);
    END IF;
    
    IF TIPO_RECORRENCIA = 3 THEN
		SET DATA_RETORNO = DATE_ADD(DT_INICIO, INTERVAL QTD_RECORRENCIAS MONTH);
    END IF;
    
    IF TIPO_RECORRENCIA = 4 THEN
		SET DATA_RETORNO = DATE_ADD(DT_INICIO, INTERVAL QTD_RECORRENCIAS YEAR);
    END IF;
    
    RETURN DATA_RETORNO;
END
//

DELIMITER //
DROP FUNCTION IF EXISTS QTD_RECORRENCIAS;
CREATE FUNCTION QTD_RECORRENCIAS(DT_INICIO DATETIME, DT_ATUAL DATETIME, TIPO_RECORRENCIA INT,
	INTERVALO INT) RETURNS INT DETERMINISTIC
BEGIN
	DECLARE oCOUNT INT DEFAULT 0;
    
    WHILE DT_INICIO <= DT_ATUAL DO
        IF TIPO_RECORRENCIA = 1 THEN
			SET DT_INICIO = DATE_ADD(DT_INICIO, INTERVAL INTERVALO DAY);
		END IF;
		
		IF TIPO_RECORRENCIA = 2 THEN
			SET DT_INICIO = DATE_ADD(DT_INICIO, INTERVAL INTERVALO WEEK);
		END IF;
		
		IF TIPO_RECORRENCIA = 3 THEN
			SET DT_INICIO = DATE_ADD(DT_INICIO, INTERVAL INTERVALO MONTH);
		END IF;
		
		IF TIPO_RECORRENCIA = 4 THEN
			SET DT_INICIO = DATE_ADD(DT_INICIO, INTERVAL INTERVALO YEAR);
		END IF;
        
        SET oCOUNT = oCOUNT + 1;
    END WHILE;
    
    RETURN oCOUNT;
END 
//

DELIMITER //
DROP FUNCTION IF EXISTS ULTIMA_RECORRENCIA;
CREATE FUNCTION ULTIMA_RECORRENCIA(TIPO INT, E_CODIGO INT) RETURNS DATETIME DETERMINISTIC
BEGIN
	DECLARE DT_ULTIMA DATETIME;
    
	IF TIPO = 1 THEN
		SELECT MAX(DATA_RECORRENCIA) INTO DT_ULTIMA FROM LEMBRETE_RECORRENCIA WHERE FK_LEMBRETE = E_CODIGO;
    END IF;
    
    IF TIPO = 2 THEN
        SELECT MAX(DATA_INICIO) INTO DT_ULTIMA FROM EVENTO_RECORRENCIA WHERE FK_EVENTO = E_CODIGO;
    END IF;
    
    RETURN DT_ULTIMA;
END
//