DELIMITER //
-- DROP PROCEDURE NOTIFICACAO;
CREATE PROCEDURE NOTIFICACAO(IN COD INT)
BEGIN
	SELECT COD_RECORRENCIA, TITULO FROM LEMBRETE_RECORRENCIA LEFT JOIN LEMBRETE ON FK_LEMBRETE = COD_LEMBRETE WHERE DATA_RECORRENCIA = SUBTIME(NOW(), SECOND(NOW())) AND FK_USUARIO = COD AND EXCLUIDO = FALSE AND CONCLUIDO = FALSE
    UNION SELECT COD_RECORRENCIA, TITULO FROM EVENTO_RECORRENCIA LEFT JOIN EVENTO ON FK_EVENTO = COD_EVENTO WHERE EVENTO_RECORRENCIA.DATA_INICIO = SUBTIME(NOW(), SECOND(NOW())) AND FK_USUARIO = COD AND EXCLUIDO = FALSE;
END
//