DELIMITER //
DROP PROCEDURE NOTIFICACAO;
CREATE PROCEDURE NOTIFICACAO()
BEGIN
	SELECT COD_RECORRENCIA, TITULO FROM LEMBRETE_RECORRENCIA LEFT JOIN LEMBRETE ON FK_LEMBRETE = COD_LEMBRETE WHERE DATA_RECORRENCIA = NOW();
    SELECT COD_RECORRENCIA, TITULO FROM EVENTO_RECORRENCIA LEFT JOIN EVENTO ON FK_EVENTO = COD_EVENTO WHERE EVENTO_RECORRENCIA.DATA_INICIO = NOW();
END
//