DELIMITER // 
CREATE PROCEDURE EMAIL_EXISTE(IN UEMAIL VARCHAR(255), OUT RESULT BIT)
BEGIN 
	DECLARE NUMERO_REGISTROS INT;  
	SELECT COUNT(0) INTO NUMERO_REGISTROS FROM USUARIO WHERE EMAIL = UEMAIL;        
           
    IF NUMERO_REGISTROS > 0 THEN               
        SET RESULT = 1;        
    ELSE                 
        SET RESULT = 0;        
	END IF;    
END 
//

DELIMITER // 
CREATE PROCEDURE ADICIONAR_USUARIO(IN UEMAIL VARCHAR(255), IN UNOME VARCHAR(255),             
	IN USOBRENOME VARCHAR(255), IN USENHA VARCHAR(255))
BEGIN                                                                                  
	IF USOBRENOME IS NULL OR USOBRENOME = '' THEN                                      
		INSERT INTO USUARIO (EMAIL,NOME,SENHA) VALUES (UEMAIL,UNOME,USENHA);         
	ELSE                                                                             
		INSERT INTO USUARIO (EMAIL,NOME,SOBRENOME,SENHA) VALUES (UEMAIL,UNOME,USOBRENOME,USENHA);                                  
	END IF;                                                                         
END 
//

DELIMITER //
DROP PROCEDURE IF EXISTS MARCAR_EVENTOS;
CREATE PROCEDURE MARCAR_EVENTOS()
BEGIN
	DECLARE dtIni DATETIME;
    DECLARE dtFim DATETIME;
    DECLARE eCod INT;
    DECLARE tRepeticao INT;
    DECLARE nInterval INT;
    DECLARE tSemana VARCHAR(15);
    
    DECLARE aDtIni DATETIME; -- guarda a data inicial antes de qualquer alteração
    
    DECLARE dtLimite DATETIME;
    DECLARE dtUltima DATETIME;

	DECLARE lErro INT DEFAULT 0;

	DECLARE oDados CURSOR FOR
		SELECT DATA_INICIO, DATA_FIM, COD_EVENTO, TIPO_REPETICAO, INTERVALO, DIAS_SEMANA FROM EVENTO 
        LEFT JOIN EVENTO_REPETICAO ON FK_EVENTO = COD_EVENTO
        ;
        
	-- lErro fica igual a 1 quando acabam os registros
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET lErro = 1;
        
	OPEN oDados;
    
    get_evento : LOOP
		FETCH oDados INTO dtIni, dtFim, eCod, tRepeticao, nInterval, tSemana;
        IF lErro = 1 THEN
			LEAVE get_evento;
        END IF;

		SET aDtIni = dtIni;

        CALL CALCULO_DATA_LIMITE(2, eCod, @dt_limite);
        SELECT @dt_limite INTO dtLimite;

        SET dtUltima = ULTIMA_RECORRENCIA(2, eCod);

        IF dtUltima IS NULL THEN
			IF tRepeticao != 2 THEN
				INSERT INTO EVENTO_RECORRENCIA (DATA_INICIO, DATA_FIM, FK_EVENTO) VALUES (dtIni, dtFim, eCod);
			ELSE
				CALL INSERT_SEMANA(2, dtIni, dtFim, eCod, tSemana);
			END IF;
            SET dtUltima = dtIni; 
        END IF;

        SET dtIni = dtUltima;
        SET dtFim = DATE_ADD(dtIni, INTERVAL DATEDIFF(dtFim, aDtIni) DAY);

        WHILE dtIni < dtLimite DO
            SET dtIni = CALCULO_RECORRENCIA(dtIni, nInterval, tRepeticao);
            SET dtFim = CALCULO_RECORRENCIA(dtFim, nInterval, tRepeticao);
            
            IF tRepeticao != 2 THEN
				INSERT INTO EVENTO_RECORRENCIA (DATA_INICIO, DATA_FIM, FK_EVENTO) VALUES (dtIni, dtFim, eCod);
			ELSE
				CALL INSERT_SEMANA(2, dtIni, dtFim, eCod, tSemana);
			END IF;
		END WHILE;
	END LOOP get_evento;
END
//

DELIMITER //
DROP PROCEDURE IF EXISTS MARCAR_LEMBRETES;
CREATE PROCEDURE MARCAR_LEMBRETES()
BEGIN
	DECLARE dtIni DATETIME;
    DECLARE dtFim DATETIME;
    DECLARE eCod INT;
    DECLARE tRepeticao INT;
    DECLARE nInterval INT;
    DECLARE tSemana VARCHAR(15);
    
    DECLARE dtLimite DATETIME;
    DECLARE dtUltima DATETIME;

	DECLARE lErro INT DEFAULT 0;

	DECLARE oDados CURSOR FOR
		SELECT HORARIO, HORARIO_FIM, COD_LEMBRETE, TIPO_REPETICAO, INTERVALO, DIAS_SEMANA FROM LEMBRETE 
        LEFT JOIN LEMBRETE_REPETICAO ON FK_LEMBRETE = COD_LEMBRETE
        ;
        
	-- lErro fica igual a 1 quando acabam os registros
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET lErro = 1;
        
	OPEN oDados;
    
    get_evento : LOOP
		FETCH oDados INTO dtIni, dtFim, eCod, tRepeticao, nInterval, tSemana;
        IF lErro = 1 THEN
			LEAVE get_evento;
        END IF;

        CALL CALCULO_DATA_LIMITE(1, eCod, @dt_limite);
        SELECT @dt_limite INTO dtLimite;

        SET dtUltima = ULTIMA_RECORRENCIA(1, eCod);

        IF dtUltima IS NULL THEN
			IF tRepeticao != 2 THEN
				INSERT INTO LEMBRETE_RECORRENCIA (DATA_RECORRENCIA, FK_LEMBRETE) VALUES (dtIni, eCod);
			ELSE
				CALL INSERT_SEMANA(1, dtIni, null, eCod, tSemana);
			END IF;
            SET dtUltima = dtIni; 
        END IF;

        SET dtIni = dtUltima;

		SELECT dtIni;

        WHILE dtIni < dtLimite DO
            SET dtIni = CALCULO_RECORRENCIA(dtIni, nInterval, tRepeticao);
            SET dtFim = CALCULO_RECORRENCIA(dtFim, nInterval, tRepeticao);
            
            IF tRepeticao != 2 THEN
				INSERT INTO LEMBRETE_RECORRENCIA (DATA_RECORRENCIA, FK_LEMBRETE) VALUES (dtIni, eCod);
			ELSE
				CALL INSERT_SEMANA(1, dtIni, null, eCod, tSemana);
			END IF;
		END WHILE;
	END LOOP get_evento;
END
//

DELIMITER //
DROP PROCEDURE IF EXISTS CALCULO_DATA_LIMITE;
CREATE PROCEDURE CALCULO_DATA_LIMITE(IN TIPO INT, IN COD INT, OUT DATA_LIMITE DATETIME)
BEGIN

	DECLARE _DATA_INICIO DATETIME;
    DECLARE _TIPO_REPETICAO INT;
    DECLARE _TIPO_FIM INT;
    DECLARE _INTERVALO INT;
    DECLARE _DIA_FIM DATETIME;
    DECLARE _QTD_RECORRENCIAS INT;
    
    DECLARE _DT_LIMITE DATETIME;
    DECLARE _DT_LIMITE_QTD DATETIME;
    
    IF TIPO = 1 THEN
		SELECT
			HORARIO, TIPO_REPETICAO, TIPO_FIM_REPETICAO, INTERVALO, DIA_FIM, QTD_RECORRENCIAS
		INTO
			_DATA_INICIO, _TIPO_REPETICAO, _TIPO_FIM, _INTERVALO, _DIA_FIM, _QTD_RECORRENCIAS
		FROM 
			LEMBRETE 
			LEFT JOIN LEMBRETE_REPETICAO ON LEMBRETE_REPETICAO.FK_LEMBRETE = COD_LEMBRETE
			LEFT JOIN LEMBRETE_FIM_REPETICAO ON LEMBRETE_FIM_REPETICAO.FK_LEMBRETE = COD_LEMBRETE
			WHERE COD_LEMBRETE = COD;
    END IF;
    
    IF TIPO = 2 THEN
		SELECT
			DATA_INICIO, TIPO_REPETICAO, TIPO_FIM_REPETICAO, INTERVALO, DIA_FIM, QTD_RECORRENCIAS
		INTO
			_DATA_INICIO, _TIPO_REPETICAO, _TIPO_FIM, _INTERVALO, _DIA_FIM, _QTD_RECORRENCIAS
		FROM 
			EVENTO 
			LEFT JOIN EVENTO_REPETICAO ON EVENTO_REPETICAO.FK_EVENTO = COD_EVENTO
			LEFT JOIN EVENTO_FIM_REPETICAO ON EVENTO_FIM_REPETICAO.FK_EVENTO = COD_EVENTO
			WHERE COD_EVENTO = COD;
    END IF;

    IF _TIPO_REPETICAO = 0 THEN
        SET DATA_LIMITE = _DATA_INICIO;
    ELSE
    
        SET _DT_LIMITE = CALCULO_RECORRENCIA(TIMESTAMP(DATE(NOW()), TIME(_DATA_INICIO)), 
			_INTERVALO * 10, _TIPO_REPETICAO);

        IF _TIPO_FIM = 0 THEN
            SET DATA_LIMITE = _DT_LIMITE;
        END IF;

        IF _TIPO_FIM = 1 THEN
            IF _DT_LIMITE < _DIA_FIM THEN
                SET DATA_LIMITE = _DT_LIMITE;
            ELSE
                SET DATA_LIMITE = _DIA_FIM;
            END IF;
        END IF;

        IF _TIPO_FIM = 2 THEN

            SET _DT_LIMITE_QTD = CALCULO_RECORRENCIA(_DATA_INICIO, _INTERVALO * _QTD_RECORRENCIAS, _TIPO_REPETICAO);

            IF _DT_LIMITE < _DT_LIMITE_QTD THEN
                SET DATA_LIMITE = _DT_LIMITE;
            ELSE 
                SET DATA_LIMITE = _DT_LIMITE_QTD;
            END IF;
        END IF;
    END IF;
END
//

DELIMITER //
DROP PROCEDURE IF EXISTS INSERT_SEMANA;
CREATE PROCEDURE INSERT_SEMANA(IN TIPO INT, IN DATA_INICIO DATETIME, IN DATA_FIM DATETIME, IN COD INT, IN SEMANA VARCHAR(15))
BEGIN

    DECLARE P_SEMANA_INICIO DATETIME;
    DECLARE P_SEMANA_FIM DATETIME;
    DECLARE A_DATA_INICIO DATETIME;
    DECLARE A_DATA_FIM DATETIME;

    DECLARE N_CONT INT DEFAULT 1;
    DECLARE A_DIA_SEMANA VARCHAR(1); 

    SELECT 
        DATE_SUB(DATA_INICIO, INTERVAL (DAYOFWEEK(DATA_INICIO) - 1)  DAY), 
        DATE_SUB(DATA_FIM, INTERVAL (DAYOFWEEK(DATA_FIM) - 1) DAY)
    INTO 
        P_SEMANA_INICIO, P_SEMANA_FIM;

    WHILE N_CONT <= 7 DO
        
        SET A_DIA_SEMANA = SUBSTRING_INDEX(SUBSTRING_INDEX(SEMANA, ',', N_CONT), ',', -1);

        IF A_DIA_SEMANA = 1 THEN

			SET A_DATA_INICIO = DATE_ADD(P_SEMANA_INICIO, INTERVAL (N_CONT - 1) DAY);
            SET A_DATA_FIM = DATE_ADD(P_SEMANA_FIM, INTERVAL (N_CONT - 1) DAY);

			IF A_DATA_INICIO < DATA_INICIO THEN
				SET A_DATA_INICIO = DATE_ADD(A_DATA_INICIO, INTERVAL 1 WEEK);
            END IF;
            
            IF A_DATA_FIM < DATA_FIM THEN
				SET A_DATA_FIM = DATE_ADD(A_DATA_FIM, INTERVAL 1 WEEK);
            END IF;

			IF TIPO = 1 THEN
				INSERT INTO 
					LEMBRETE_RECORRENCIA (DATA_RECORRENCIA, FK_LEMBRETE) 
				VALUES (
					A_DATA_INICIO, COD);
            END IF;
            IF TIPO = 2 THEN
				INSERT INTO 
					EVENTO_RECORRENCIA (DATA_INICIO, DATA_FIM, FK_EVENTO) 
				VALUES (
					A_DATA_INICIO, A_DATA_FIM, COD);
            END IF;

        END IF;

        SET N_CONT = N_CONT + 1;
    END WHILE;
END 
//

DELIMITER //
DROP PROCEDURE IF EXISTS CARREGAR_MES;
CREATE PROCEDURE CARREGAR_MES(IN DATA_MES DATETIME)
BEGIN
	SELECT
		1 TIPO, DAY(DATA_RECORRENCIA) DIA, COD_RECORRENCIA, TITULO, DATA_RECORRENCIA DATA_INICIO, NULL DATA_FIM, 
		CONCLUIDO, FK_LEMBRETE CODIGO
    FROM 
		LEMBRETE_RECORRENCIA 
	INNER JOIN
		LEMBRETE ON COD_LEMBRETE = FK_LEMBRETE
	WHERE 
		MONTH(DATA_RECORRENCIA) = MONTH(DATA_MES) AND YEAR(DATA_RECORRENCIA) = YEAR(DATA_MES) AND EXCLUIDO = FALSE
    UNION SELECT 
		2 TIPO, DAY(EVENTO_RECORRENCIA.DATA_INICIO), COD_RECORRENCIA, TITULO, EVENTO_RECORRENCIA.DATA_INICIO, 
        EVENTO_RECORRENCIA.DATA_FIM, NULL, FK_EVENTO 
	FROM 
		EVENTO_RECORRENCIA 
	INNER JOIN 
		EVENTO ON COD_EVENTO = FK_EVENTO
	WHERE 
		MONTH(EVENTO_RECORRENCIA.DATA_INICIO) = MONTH(DATA_MES) AND 
        YEAR(EVENTO_RECORRENCIA.DATA_INICIO) = YEAR(DATA_MES) AND EXCLUIDO = FALSE
	ORDER BY DATA_INICIO;
END
//

DELIMITER //
DROP PROCEDURE IF EXISTS CARREGAR_DIA;
CREATE PROCEDURE CARREGAR_DIA(IN DIA DATETIME)
BEGIN
	SELECT
		1 TIPO, TITULO, DATA_RECORRENCIA DATA_INICIO, NULL DATA_FIM, DIA_TODO, CONCLUIDO, FK_LEMBRETE CODIGO
    FROM 
		LEMBRETE_RECORRENCIA 
	INNER JOIN
		LEMBRETE ON COD_LEMBRETE = FK_LEMBRETE
	WHERE 
		DATE(DATA_RECORRENCIA) = DATE(DIA) AND EXCLUIDO = FALSE
    UNION SELECT 
		2 TIPO, TITULO, EVENTO_RECORRENCIA.DATA_INICIO, EVENTO_RECORRENCIA.DATA_FIM, DIA_TODO, NULL, FK_EVENTO 
	FROM 
		EVENTO_RECORRENCIA 
	INNER JOIN 
		EVENTO ON COD_EVENTO = FK_EVENTO
	WHERE 
		DATE(EVENTO_RECORRENCIA.DATA_INICIO) = DATE(DIA) AND EXCLUIDO = FALSE
	ORDER BY DATA_INICIO;
END
//
