DELIMITER //
-- DROP TRIGGER IF EXISTS UPD_EVENTO_RECORRENCIA;
CREATE TRIGGER UPD_EVENTO_RECORRENCIA AFTER INSERT ON EVENTO_FIM_REPETICAO
FOR EACH ROW
BEGIN
	CALL MARCAR_EVENTOS();
END
//

DELIMITER //
-- DROP TRIGGER IF EXISTS UPD_LEMBRETE_RECORRENCIA;
CREATE TRIGGER UPD_LEMBRETE_RECORRENCIA AFTER INSERT ON LEMBRETE_FIM_REPETICAO
FOR EACH ROW
BEGIN
	CALL MARCAR_LEMBRETES();
END
//

DELIMITER //
-- DROP TRIGGER IF EXISTS UPD_META_SEMANA;
CREATE TRIGGER UPD_META_SEMANA AFTER INSERT ON META
FOR EACH ROW
BEGIN
	CALL MARCAR_METAS();
END
//

DELIMITER //
CREATE TRIGGER CRIA_CONFIG_USUARIO AFTER INSERT ON USUARIO
FOR EACH ROW
BEGIN
	INSERT INTO USUARIO_CONFIGURACOES (HORARIO_TAREFA_INICIO, HORARIO_TAREFA_FIM, FK_USUARIO) VALUES ('13:00:00', '16:00:00', new.COD_USUARIO);
END
//

DELIMITER //
CREATE TRIGGER UPD_TAREFA BEFORE UPDATE ON TAREFA FOR EACH ROW
BEGIN
	IF new.CONCLUIDO = 1 THEN
		SET new.DATA_CONCLUIDO = DATE(NOW());
    END IF;
END
//