DELIMITER //
-- DROP TRIGGER IF EXISTS UPD_EVENTO_RECORRENCIA;
CREATE TRIGGER UPD_EVENTO_RECORRENCIA AFTER INSERT ON EVENTO_FIM_REPETICAO
FOR EACH ROW
BEGIN
	CALL MARCAR_EVENTOS();
END
//

DELIMITER //
-- DROP TRIGGER IF EXISTS UPD_LEMBRETE_RECORRENCIA;
CREATE TRIGGER UPD_LEMBRETE_RECORRENCIA AFTER INSERT ON LEMBRETE_FIM_REPETICAO
FOR EACH ROW
BEGIN
	CALL MARCAR_LEMBRETES();
END
//

DELIMITER //
-- DROP TRIGGER IF EXISTS UPD_META_SEMANA;
CREATE TRIGGER UPD_META_SEMANA AFTER INSERT ON META
FOR EACH ROW
BEGIN
	CALL MARCAR_METAS();
END
//

DELIMITER //
CREATE TRIGGER CRIA_CONFIG_USUARIO AFTER INSERT ON USUARIO
FOR EACH ROW
BEGIN
	INSERT INTO USUARIO_CONFIGURACOES (HORARIO_TAREFA_INICIO, HORARIO_TAREFA_FIM, FK_USUARIO) VALUES ('13:00:00', '16:00:00', new.COD_USUARIO);
END
//

DELIMITER //
-- DROP TRIGGER UPD_TAREFA;
CREATE TRIGGER UPD_TAREFA BEFORE UPDATE ON TAREFA FOR EACH ROW
BEGIN
	IF new.CONCLUIDO = 1 THEN
		SET new.DATA_CONCLUIDO = NOW();
    END IF;
END
//

DELIMITER //
CREATE TRIGGER DELETA_MARCADOR BEFORE DELETE ON MARCADOR FOR EACH ROW
BEGIN
	UPDATE TAREFA SET FK_NOME_MARCADOR = NULL WHERE FK_NOME_MARCADOR = old.NOME_MARCADOR;
END
//

DELIMITER //
CREATE TRIGGER DELETA_META BEFORE DELETE ON META FOR EACH ROW
BEGIN
	DELETE FROM META_SEMANA WHERE FK_META = old.COD_META;
	DELETE FROM META_RECORRENCIA WHERE FK_META = old.COD_META;
END
//