DELIMITER //
-- DROP TRIGGER IF EXISTS UPD_EVENTO_RECORRENCIA;
CREATE TRIGGER UPD_EVENTO_RECORRENCIA AFTER INSERT ON EVENTO_FIM_REPETICAO
FOR EACH ROW
BEGIN
	CALL MARCAR_EVENTOS();
END
//

DELIMITER //
-- DROP TRIGGER IF EXISTS UPD_LEMBRETE_RECORRENCIA;
CREATE TRIGGER UPD_LEMBRETE_RECORRENCIA AFTER INSERT ON LEMBRETE_FIM_REPETICAO
FOR EACH ROW
BEGIN
	CALL MARCAR_LEMBRETES();
END
//

DELIMITER //
DROP TRIGGER IF EXISTS UPD_META_SEMANA;
CREATE TRIGGER UPD_META_SEMANA AFTER INSERT ON META
FOR EACH ROW
BEGIN
	CALL MARCAR_METAS();
END
//