
DROP TABLE IF EXISTS `HORARIO_LEMBRETE`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `HORARIO_LEMBRETE` (
  `HL_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `HL_HORARIO_INICIO` datetime DEFAULT NULL,
  `HL_HORARIO_FIM` datetime DEFAULT NULL,
  `HL_DATA_REPETICAO` datetime DEFAULT NULL,
  `HL_INTERVALO_MINUTOS` int(11) DEFAULT NULL,
  `HL_RECORRENCIA` int(11) DEFAULT NULL,
  `HL_SEMANA_DIA` int(11) DEFAULT NULL,
  `HL_QTD_REPETE` int(11) DEFAULT NULL,
  `FK_LEMBRETE` int(11) DEFAULT NULL,
  PRIMARY KEY (`HL_CODIGO`),
  KEY `FK_CODIGO_LEMBRETE` (`FK_LEMBRETE`),
  CONSTRAINT `FK_CODIGO_LEMBRETE` FOREIGN KEY (`FK_LEMBRETE`) REFERENCES `LEMBRETE` (`LCOD_LEMBRETE`)
) ENGINE=InnoDB AUTO_INCREMENT=63 DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS `LEMBRETE`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `LEMBRETE` (
  `LCOD_LEMBRETE` int(11) NOT NULL AUTO_INCREMENT,
  `LEMBRETE` text,
  `LDIA_TODO` bit(1) DEFAULT NULL,
  `L_STATUS` varchar(20) DEFAULT NULL,
  `LRECORRENCIA_TIPO` int(11) DEFAULT NULL,
  `FK_USUARIO` int(11) DEFAULT NULL,
  PRIMARY KEY (`LCOD_LEMBRETE`),
  KEY `FK_USUARIO` (`FK_USUARIO`),
  CONSTRAINT `FK_USUARIO` FOREIGN KEY (`FK_USUARIO`) REFERENCES `USUARIO` (`UCODIGO`)
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS `USUARIO`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `USUARIO` (
  `UCODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `UEMAIL` varchar(255) NOT NULL,
  `UNOME` varchar(255) DEFAULT NULL,
  `USOBRENOME` varchar(255) DEFAULT NULL,
  `USENHA` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`UCODIGO`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=latin1;
-- MySQL dump 10.13  Distrib 5.7.24, for Linux (x86_64)
--
-- Host: localhost    Database: CYBER_LIFE
-- ------------------------------------------------------
-- Server version	5.7.24-0ubuntu0.18.04.1

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `HORARIO_LEMBRETE`
--

DROP TABLE IF EXISTS `HORARIO_LEMBRETE`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `HORARIO_LEMBRETE` (
  `HL_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `DATA_LEMBRETE` datetime DEFAULT NULL,
  `DATA_FINAL_LEMBRETE` datetime DEFAULT NULL,
  `HORARIO_INICIO` time DEFAULT NULL,
  `HORARIO_FIM` time DEFAULT NULL,
  `HL_INTERVALO_MINUTOS` int(11) DEFAULT NULL,
  `HL_RECORRENCIA` int(11) DEFAULT NULL,
  `HL_SEMANA_DIA` int(11) DEFAULT NULL,
  `HL_QTD_REPETE` int(11) DEFAULT NULL,
  `FK_LEMBRETE` int(11) DEFAULT NULL,
  PRIMARY KEY (`HL_CODIGO`),
  KEY `FK_CODIGO_LEMBRETE` (`FK_LEMBRETE`),
  CONSTRAINT `FK_CODIGO_LEMBRETE` FOREIGN KEY (`FK_LEMBRETE`) REFERENCES `LEMBRETE` (`LCOD_LEMBRETE`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `HORARIO_LEMBRETE`
--

LOCK TABLES `HORARIO_LEMBRETE` WRITE;
/*!40000 ALTER TABLE `HORARIO_LEMBRETE` DISABLE KEYS */;
INSERT INTO `HORARIO_LEMBRETE` VALUES (1,'2018-11-25 18:33:37',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1),(2,'2018-11-25 18:46:11',NULL,NULL,NULL,NULL,NULL,NULL,NULL,2);
/*!40000 ALTER TABLE `HORARIO_LEMBRETE` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `LEMBRETE`
--

DROP TABLE IF EXISTS `LEMBRETE`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `LEMBRETE` (
  `LCOD_LEMBRETE` int(11) NOT NULL AUTO_INCREMENT,
  `TITULO` varchar(255) DEFAULT NULL,
  `ATIVO` bit(1) DEFAULT NULL,
  `TIPO_RECORRENCIA` int(11) DEFAULT NULL,
  `TIPO_REPETICAO` int(11) DEFAULT NULL,
  `FK_USUARIO` int(11) DEFAULT NULL,
  PRIMARY KEY (`LCOD_LEMBRETE`),
  KEY `FK_USUARIO` (`FK_USUARIO`),
  CONSTRAINT `FK_USUARIO` FOREIGN KEY (`FK_USUARIO`) REFERENCES `USUARIO` (`UCODIGO`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `LEMBRETE`
--

LOCK TABLES `LEMBRETE` WRITE;
/*!40000 ALTER TABLE `LEMBRETE` DISABLE KEYS */;
INSERT INTO `LEMBRETE` VALUES (1,'TESTES',NULL,NULL,NULL,1),(2,'OUTRO TESTE',NULL,NULL,NULL,1);
/*!40000 ALTER TABLE `LEMBRETE` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `USUARIO`
--

DROP TABLE IF EXISTS `USUARIO`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `USUARIO` (
  `UCODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `UEMAIL` varchar(255) NOT NULL,
  `UNOME` varchar(255) DEFAULT NULL,
  `USOBRENOME` varchar(255) DEFAULT NULL,
  `USENHA` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`UCODIGO`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `USUARIO`
--

LOCK TABLES `USUARIO` WRITE;
/*!40000 ALTER TABLE `USUARIO` DISABLE KEYS */;
INSERT INTO `USUARIO` VALUES (1,'FJJFFJ','JEFTER',NULL,NULL);
/*!40000 ALTER TABLE `USUARIO` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Temporary table structure for view `VIEW_CARREGAR_LEMBRETES`
--

DROP TABLE IF EXISTS `VIEW_CARREGAR_LEMBRETES`;
/*!50001 DROP VIEW IF EXISTS `VIEW_CARREGAR_LEMBRETES`*/;
SET @saved_cs_client     = @@character_set_client;
SET character_set_client = utf8;
/*!50001 CREATE VIEW `VIEW_CARREGAR_LEMBRETES` AS SELECT 
 1 AS `UCODIGO`,
 1 AS `LCOD_LEMBRETE`,
 1 AS `TITULO`,
 1 AS `ATIVO`,
 1 AS `TIPO_RECORRENCIA`,
 1 AS `TIPO_REPETICAO`,
 1 AS `HL_CODIGO`,
 1 AS `FK_LEMBRETE`,
 1 AS `DATA_LEMBRETE`,
 1 AS `DATA_FINAL_LEMBRETE`,
 1 AS `HORARIO_INICIO`,
 1 AS `HORARIO_FIM`,
 1 AS `HL_INTERVALO_MINUTOS`,
 1 AS `HL_RECORRENCIA`,
 1 AS `HL_SEMANA_DIA`,
 1 AS `HL_QTD_REPETE`*/;
SET character_set_client = @saved_cs_client;

--
-- Temporary table structure for view `VIEW_INICIA_SESSAO`
--

DROP TABLE IF EXISTS `VIEW_INICIA_SESSAO`;
/*!50001 DROP VIEW IF EXISTS `VIEW_INICIA_SESSAO`*/;
SET @saved_cs_client     = @@character_set_client;
SET character_set_client = utf8;
/*!50001 CREATE VIEW `VIEW_INICIA_SESSAO` AS SELECT 
 1 AS `UCODIGO`,
 1 AS `UNOME`,
 1 AS `USOBRENOME`,
 1 AS `UEMAIL`,
 1 AS `USENHA`*/;
SET character_set_client = @saved_cs_client;

--
-- Final view structure for view `VIEW_CARREGAR_LEMBRETES`
--

/*!50001 DROP VIEW IF EXISTS `VIEW_CARREGAR_LEMBRETES`*/;
/*!50001 SET @saved_cs_client          = @@character_set_client */;
/*!50001 SET @saved_cs_results         = @@character_set_results */;
/*!50001 SET @saved_col_connection     = @@collation_connection */;
/*!50001 SET character_set_client      = utf8 */;
/*!50001 SET character_set_results     = utf8 */;
/*!50001 SET collation_connection      = utf8_general_ci */;
/*!50001 CREATE ALGORITHM=UNDEFINED */
/*!50013 DEFINER=`root`@`localhost` SQL SECURITY DEFINER */
/*!50001 VIEW `VIEW_CARREGAR_LEMBRETES` AS select `USUARIO`.`UCODIGO` AS `UCODIGO`,`LEMBRETE`.`LCOD_LEMBRETE` AS `LCOD_LEMBRETE`,`LEMBRETE`.`TITULO` AS `TITULO`,`LEMBRETE`.`ATIVO` AS `ATIVO`,`LEMBRETE`.`TIPO_RECORRENCIA` AS `TIPO_RECORRENCIA`,`LEMBRETE`.`TIPO_REPETICAO` AS `TIPO_REPETICAO`,`HORARIO_LEMBRETE`.`HL_CODIGO` AS `HL_CODIGO`,`HORARIO_LEMBRETE`.`FK_LEMBRETE` AS `FK_LEMBRETE`,`HORARIO_LEMBRETE`.`DATA_LEMBRETE` AS `DATA_LEMBRETE`,`HORARIO_LEMBRETE`.`DATA_FINAL_LEMBRETE` AS `DATA_FINAL_LEMBRETE`,`HORARIO_LEMBRETE`.`HORARIO_INICIO` AS `HORARIO_INICIO`,`HORARIO_LEMBRETE`.`HORARIO_FIM` AS `HORARIO_FIM`,`HORARIO_LEMBRETE`.`HL_INTERVALO_MINUTOS` AS `HL_INTERVALO_MINUTOS`,`HORARIO_LEMBRETE`.`HL_RECORRENCIA` AS `HL_RECORRENCIA`,`HORARIO_LEMBRETE`.`HL_SEMANA_DIA` AS `HL_SEMANA_DIA`,`HORARIO_LEMBRETE`.`HL_QTD_REPETE` AS `HL_QTD_REPETE` from ((`LEMBRETE` join `USUARIO` on((`LEMBRETE`.`FK_USUARIO` = `USUARIO`.`UCODIGO`))) join `HORARIO_LEMBRETE` on((`LEMBRETE`.`LCOD_LEMBRETE` = `HORARIO_LEMBRETE`.`FK_LEMBRETE`))) where (cast(`HORARIO_LEMBRETE`.`DATA_LEMBRETE` as date) = cast(now() as date)) */;
/*!50001 SET character_set_client      = @saved_cs_client */;
/*!50001 SET character_set_results     = @saved_cs_results */;
/*!50001 SET collation_connection      = @saved_col_connection */;

--
-- Final view structure for view `VIEW_INICIA_SESSAO`
--

/*!50001 DROP VIEW IF EXISTS `VIEW_INICIA_SESSAO`*/;
/*!50001 SET @saved_cs_client          = @@character_set_client */;
/*!50001 SET @saved_cs_results         = @@character_set_results */;
/*!50001 SET @saved_col_connection     = @@collation_connection */;
/*!50001 SET character_set_client      = utf8 */;
/*!50001 SET character_set_results     = utf8 */;
/*!50001 SET collation_connection      = utf8_general_ci */;
/*!50001 CREATE ALGORITHM=UNDEFINED */
/*!50013 DEFINER=`root`@`localhost` SQL SECURITY DEFINER */
/*!50001 VIEW `VIEW_INICIA_SESSAO` AS select `USUARIO`.`UCODIGO` AS `UCODIGO`,`USUARIO`.`UNOME` AS `UNOME`,`USUARIO`.`USOBRENOME` AS `USOBRENOME`,`USUARIO`.`UEMAIL` AS `UEMAIL`,`USUARIO`.`USENHA` AS `USENHA` from `USUARIO` */;
/*!50001 SET character_set_client      = @saved_cs_client */;
/*!50001 SET character_set_results     = @saved_cs_results */;
/*!50001 SET collation_connection      = @saved_col_connection */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2018-11-25 19:01:06
