create table EVENTO(
	COD_EVENTO int not null primary key auto_increment,
    TITULO varchar(100) not null, 
    DATA_INICIO datetime not null,
    DATA_FIM datetime not null,
    LOCAL_EVENTO varchar(150),
    DESCRICAO varchar(255),
    TIPO_REPETICAO int,
    TIPO_FIM_REPETICAO int,
    FK_USUARIO int,
    foreign key (FK_USUARIO) references USUARIO(UCODIGO)
);

create table E_REPETIR(
	COD_REPETICAO int not null primary key auto_increment,
    INTERVALO int not null,
    DIAS_SEMANA varchar(15),
    FK_EVENTO int,
    unique key UNIQUE_EVENTO (FK_EVENTO),
    foreign key (FK_EVENTO) references EVENTO(COD_EVENTO)
);

create table E_FIM_REPETICAO(
	COD_FIM_REPETICAO int not null primary key auto_increment,
    DIA_FIM datetime,
    QTD_RECORRENCIAS int,
    FK_EVENTO int,
    unique key UNIQUE_EVENTO (FK_EVENTO),
    foreign key (FK_EVENTO) references EVENTO(COD_EVENTO)
);

DROP TABLE IF EXISTS `HORARIO_LEMBRETE`;
CREATE TABLE `HORARIO_LEMBRETE` (
  `HL_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `DATA_LEMBRETE` datetime DEFAULT NULL,
  `DATA_FINAL_LEMBRETE` datetime DEFAULT NULL,
  `HORARIO_INICIO` time DEFAULT NULL,
  `HORARIO_FIM` time DEFAULT NULL,
  `HL_INTERVALO_MINUTOS` int(11) DEFAULT NULL,
  `HL_RECORRENCIA` int(11) DEFAULT NULL,
  `HL_SEMANA_DIA` int(11) DEFAULT NULL,
  `HL_QTD_REPETE` int(11) DEFAULT NULL,
  `FK_LEMBRETE` int(11) DEFAULT NULL,
  PRIMARY KEY (`HL_CODIGO`),
  KEY `FK_CODIGO_LEMBRETE` (`FK_LEMBRETE`),
  CONSTRAINT `FK_CODIGO_LEMBRETE` FOREIGN KEY (`FK_LEMBRETE`) REFERENCES `LEMBRETE` (`LCOD_LEMBRETE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `LEMBRETE`;
CREATE TABLE `LEMBRETE` (
  `LCOD_LEMBRETE` int(11) NOT NULL AUTO_INCREMENT,
  `TITULO` varchar(255) DEFAULT NULL,
  `ATIVO` bit(1) DEFAULT NULL,
  `TIPO_RECORRENCIA` int(11) DEFAULT NULL,
  `TIPO_REPETICAO` int(11) DEFAULT NULL,
  `FK_USUARIO` int(11) DEFAULT NULL,
  PRIMARY KEY (`LCOD_LEMBRETE`),
  KEY `FK_USUARIO` (`FK_USUARIO`),
  CONSTRAINT `FK_USUARIO` FOREIGN KEY (`FK_USUARIO`) REFERENCES `USUARIO` (`UCODIGO`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS `USUARIO`;
CREATE TABLE `USUARIO` (
  `UCODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `UEMAIL` varchar(255) NOT NULL,
  `UNOME` varchar(255) DEFAULT NULL,
  `USOBRENOME` varchar(255) DEFAULT NULL,
  `USENHA` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`UCODIGO`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;
