  DROP TABLE IF EXISTS `USUARIO`;
  CREATE TABLE `USUARIO` (
    `UCODIGO` int(11) NOT NULL AUTO_INCREMENT,
    `UEMAIL` varchar(255) NOT NULL,
    `UNOME` varchar(255) DEFAULT NULL,
    `USOBRENOME` varchar(255) DEFAULT NULL,
    `USENHA` varchar(255) DEFAULT NULL,
    `UATIVO` BIT, 
    PRIMARY KEY (`UCODIGO`)
  ) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `EVENTO`;
CREATE TABLE `EVENTO` (
  `COD_EVENTO` int(11) NOT NULL AUTO_INCREMENT,
  `TITULO` varchar(100) NOT NULL,
  `DATA_INICIO` datetime NOT NULL,
  `DATA_FIM` datetime NOT NULL,
  `DIA_TODO` bit NOT NULL,
  `LOCAL_EVENTO` varchar(150) DEFAULT NULL,
  `DESCRICAO` varchar(255) DEFAULT NULL,
  `TIPO_REPETICAO` int(11) DEFAULT NULL,
  `TIPO_FIM_REPETICAO` int(11) DEFAULT NULL,
  `FK_USUARIO` int(11) DEFAULT NULL,
  PRIMARY KEY (`COD_EVENTO`),
  KEY `FK_USUARIO` (`FK_USUARIO`),
  CONSTRAINT `EVENTO_ibfk_1` FOREIGN KEY (`FK_USUARIO`) REFERENCES `USUARIO` (`UCODIGO`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `E_FIM_REPETICAO`;
CREATE TABLE `E_FIM_REPETICAO` (
  `COD_FIM_REPETICAO` int(11) NOT NULL AUTO_INCREMENT,
  `DIA_FIM` datetime DEFAULT NULL,
  `QTD_RECORRENCIAS` int(11) DEFAULT NULL,
  `FK_EVENTO` int(11) DEFAULT NULL,
  PRIMARY KEY (`COD_FIM_REPETICAO`),
  UNIQUE KEY `UNIQUE_EVENTO` (`FK_EVENTO`),
  CONSTRAINT `E_FIM_REPETICAO_ibfk_1` FOREIGN KEY (`FK_EVENTO`) REFERENCES `EVENTO` (`COD_EVENTO`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `E_REPETIR`;
CREATE TABLE `E_REPETIR` (
  `COD_REPETICAO` int(11) NOT NULL AUTO_INCREMENT,
  `INTERVALO` int(11) NOT NULL,
  `DIAS_SEMANA` varchar(15) DEFAULT NULL,
  `FK_EVENTO` int(11) DEFAULT NULL,
  PRIMARY KEY (`COD_REPETICAO`),
  UNIQUE KEY `UNIQUE_EVENTO` (`FK_EVENTO`),
  CONSTRAINT `E_REPETIR_ibfk_1` FOREIGN KEY (`FK_EVENTO`) REFERENCES `EVENTO` (`COD_EVENTO`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `LEMBRETE`;
CREATE TABLE `LEMBRETE` (
  `LCOD_LEMBRETE` int(11) NOT NULL AUTO_INCREMENT,
  `TITULO` varchar(255) DEFAULT NULL,
  `ATIVO` bit(1) DEFAULT NULL,
  `TIPO_RECORRENCIA` int(11) DEFAULT NULL,
  `TIPO_REPETICAO` int(11) DEFAULT NULL,
  `FK_USUARIO` int(11) DEFAULT NULL,
  PRIMARY KEY (`LCOD_LEMBRETE`),
  KEY `FK_USUARIO` (`FK_USUARIO`),
  CONSTRAINT `FK_USUARIO` FOREIGN KEY (`FK_USUARIO`) REFERENCES `USUARIO` (`UCODIGO`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `HORARIO_LEMBRETE`;
CREATE TABLE `HORARIO_LEMBRETE` (
  `HL_CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `DATA_LEMBRETE` datetime DEFAULT NULL,
  `DATA_FINAL_LEMBRETE` datetime DEFAULT NULL,
  `HORARIO_INICIO` time DEFAULT NULL,
  `HORARIO_FIM` time DEFAULT NULL,
  `HL_INTERVALO_MINUTOS` int(11) DEFAULT NULL,
  `HL_RECORRENCIA` int(11) DEFAULT NULL,
  `HL_SEMANA_DIA` int(11) DEFAULT NULL,
  `HL_QTD_REPETE` int(11) DEFAULT NULL,
  `HL_ATIVO` bit(1) DEFAULT NULL,
  `FK_LEMBRETE` int(11) DEFAULT NULL,
  PRIMARY KEY (`HL_CODIGO`),
  KEY `FK_CODIGO_LEMBRETE` (`FK_LEMBRETE`),
  CONSTRAINT `FK_CODIGO_LEMBRETE` FOREIGN KEY (`FK_LEMBRETE`) REFERENCES `LEMBRETE` (`LCOD_LEMBRETE`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;
