DELIMITER //
DROP PROCEDURE IF EXISTS TAREFA_ATUAL;
CREATE PROCEDURE TAREFA_ATUAL(IN COD_PROJETO INT, IN USUARIO INT)
BEGIN
	CALL HORARIO_TAREFAS(USUARIO);
	SELECT COD_TAREFA, DATA_INICIO, DATA_FIM, NOME_TAREFA, FK_PROJETO FROM TEMP_TAREFAS INNER JOIN TAREFA ON COD_TAREFA = FK_TAREFA WHERE FK_PROJETO = COD_PROJETO ORDER BY DATA_INICIO LIMIT 1; 
END
//

