    CREATE TEMPORARY TABLE TEMP_TAREFAS (
		TIPO INT DEFAULT 3,
        DATA_INICIO DATETIME,
        DATA_FIM DATETIME,
        FK_TAREFA INT,
        FK_USUARIO INT
    );

		SELECT COD_TAREFA, DURACAO_MINUTOS FROM TAREFA 
        INNER JOIN PROJETO ON FK_PROJETO = COD_PROJETO 
        WHERE FK_USUARIO = USUARIO ORDER BY IMPORTANCIA DESC;

        SET DATA_INICIO = CALCULO_HORA_TAREFA(USUARIO, SEC_TO_TIME(tDuracao * 60));
        SET DATA_FIM = DATE_ADD(DATA_INICIO, INTERVAL tDuracao MINUTE);
        
-- INSERT INTO TEMP_TAREFAS (DATA_INICIO, DATA_FIM, FK_TAREFA, FK_USUARIO);

SELECT *
  FROM (
SELECT CALCULO_HORA_TAREFA(1, SEC_TO_TIME(DURACAO_MINUTOS * 60)) INICIO, DATE_ADD(CALCULO_HORA_TAREFA(1, SEC_TO_TIME(DURACAO_MINUTOS * 60)) , INTERVAL DURACAO_MINUTOS MINUTE) FIM,
       COD_TAREFA, 1 USUARIO
  FROM TAREFA
 INNER JOIN PROJETO ON FK_PROJETO = COD_PROJETO 
 WHERE FK_USUARIO = 1
 ORDER BY IMPORTANCIA DESC) TEMP
 WHERE '2019-05-30 13:40:00' BETWEEN INICIO AND FIM;
@@ROWCOUNT

SELECT *
  FROM Motor(2, 3)